twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        'category': '@App\Twig\Categories'
        'utilisateur': '@App\Twig\Utilisateur'
        'afficher_commentaire': '@App\Twig\commentaireService'
        'articleService': '@App\Twig\Article'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true